#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Regenerate .pre-commit-hooks.yaml and this repo's own .pre-commit-config.yaml.

.pre-commit-hooks.yaml comes from upstream/.pre-commit-config.yaml:
- Remote repos: each listed hook is copied from its upstream repo at `rev`, with
  any hook-level keys from the config (args, files, stages, ...) applied on top.
  It gets `language: system` (except `language: fail` hooks, which only print a
  message), so the hook runs the binary on PATH (mise).
- `repo: local`: hooks owned by this repo, published as written. They must use
  `language: system`, `script` (entry is a script in this repo, e.g. hooks/<id>.sh)
  or `fail`.
Every hook loses the keys that make prek/pre-commit install its own copy of the
tool. Published ids and aliases must be unique; there is no renaming, so to
publish a variant of an upstream hook, copy it under `repo: local` with a new id.

.pre-commit-config.yaml (the hooks that lint this repo) comes from
self-lint.yaml: the selected hooks are copied from the freshly generated
.pre-commit-hooks.yaml as `repo: local` hooks, so this repo always lints with
its current, unreleased hook definitions.

Revs are bumped with `pre-commit autoupdate -c upstream/.pre-commit-config.yaml`
(tags or `--freeze` commit hashes both work).

Upstreams are fetched with `git fetch`, so an internal mirror / Artifactory
remote works via git config, e.g.:
    git config --global url."https://artifactory.example.com/github/".insteadOf "https://github.com/"

Usage:
    uv run scripts/sync.py          # rewrite the generated files
    uv run scripts/sync.py --check  # exit 1 if any is out of date (for CI)
"""

from __future__ import annotations

import argparse
import difflib
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
UPSTREAM = ROOT / "upstream" / ".pre-commit-config.yaml"
HOOKS_FILE = ROOT / ".pre-commit-hooks.yaml"
SELF_LINT = ROOT / "self-lint.yaml"
ROOT_CONFIG = ROOT / ".pre-commit-config.yaml"

# Keys that only matter when prek/pre-commit builds an environment for the hook.
DROP_KEYS = ("additional_dependencies", "language_version", "minimum_pre_commit_version")

# Upstream languages that need no tool, so they are kept instead of becoming `system`.
KEEP_LANGUAGES = ("fail",)

# Languages a `repo: local` hook may use (published as written).
LOCAL_LANGUAGES = ("system", "script", "unsupported_script", "fail")

SCRIPT_LANGUAGES = ("script", "unsupported_script")

VARIANT_HINT = (
    "to publish a variant of a hook, copy it under repo: local with a new id "
    "(listing the same upstream id twice doesn't work here)"
)

# Repos with nothing to mirror.
UNSUPPORTED_REPOS = ("meta", "builtin")

HOOKS_HEADER = """\
# yaml-language-server: $schema=https://www.schemastore.org/pre-commit-hooks.json
# GENERATED by scripts/sync.py from upstream/.pre-commit-config.yaml -- do not edit by hand.
# Upstream hook settings are copied with `language: system` so the tool version
# comes from mise (or whatever is on PATH); local hooks are published as written.
"""

ROOT_CONFIG_HEADER = """\
# yaml-language-server: $schema=https://www.schemastore.org/pre-commit-config.json
# GENERATED by scripts/sync.py from self-lint.yaml -- do not edit by hand.
# Lints this repo with its own current hook definitions. Run: mise run lint
"""


def git(*args: str, cwd: str) -> None:
    subprocess.run(["git", "-c", "advice.detachedHead=false", *args], cwd=cwd, check=True)


def fetch_hooks(url: str, rev: str) -> list[dict]:
    # init + fetch <rev> (instead of clone --branch) so frozen commit hashes work too.
    with tempfile.TemporaryDirectory() as tmp:
        git("init", "--quiet", cwd=tmp)
        git("fetch", "--quiet", "--depth", "1", url, rev, cwd=tmp)
        git("checkout", "--quiet", "FETCH_HEAD", cwd=tmp)
        return yaml.safe_load((Path(tmp) / ".pre-commit-hooks.yaml").read_text())


def convert(hook: dict, source: str) -> dict:
    language = hook.get("language")
    if source == "local":
        if language not in LOCAL_LANGUAGES:
            sys.exit(
                f"local hook {hook['id']!r} uses language {language!r}; "
                f"local hooks must use {', '.join(LOCAL_LANGUAGES)}"
            )
    elif language in SCRIPT_LANGUAGES:
        sys.exit(
            f"{source}:{hook['id']} runs a script from its own repo; "
            "copy the hook under repo: local and ship the script in hooks/"
        )

    out = {k: v for k, v in hook.items() if k not in DROP_KEYS}
    if source != "local" and language not in KEEP_LANGUAGES:
        out["language"] = "system"
    return out


def repo_hooks(repo: dict) -> list[tuple[dict, str]]:
    """Return (merged hook, source) pairs for one repo entry of the upstream config."""
    url = repo["repo"]
    if url in UNSUPPORTED_REPOS:
        sys.exit(f"repo: {url} has nothing to mirror; remove it from {UPSTREAM.relative_to(ROOT)}")

    if url == "local":
        for hook in repo["hooks"]:
            missing = {"id", "name", "entry", "language"} - hook.keys()
            if missing:
                sys.exit(f"local hook {hook.get('id', '?')!r} is missing {', '.join(sorted(missing))}")
        return [(hook, "local") for hook in repo["hooks"]]

    source = f"{url}@{repo['rev']}"
    upstream = {h["id"]: h for h in fetch_hooks(url, repo["rev"])}
    pairs = []
    for entry in repo["hooks"]:
        hook_id = entry["id"]
        if hook_id not in upstream:
            sys.exit(f"{source} has no hook {hook_id!r} (has: {', '.join(upstream)})")
        pairs.append(({**upstream[hook_id], **entry}, source))
    return pairs


def build_hooks() -> list[dict]:
    config = yaml.safe_load(UPSTREAM.read_text())
    hooks: list[dict] = []
    # Every published id and alias -> where it came from. `prek run <name>` and
    # `pre-commit run <name>` select hooks by id or alias, so they share one namespace.
    names: dict[str, str] = {}
    for repo in config["repos"]:
        for hook, source in repo_hooks(repo):
            where = f"{source}:{hook['id']}"
            claimed = [("id", hook["id"])]
            if hook.get("alias") and hook["alias"] != hook["id"]:
                claimed.append(("alias", hook["alias"]))
            for kind, name in claimed:
                label = f"{kind} {name!r} ({where})"
                if name in names:
                    problem = (
                        f"{label} is listed twice" if names[name] == label else f"{label} collides with {names[name]}"
                    )
                    sys.exit(f"{problem}; {VARIANT_HINT}")
                names[name] = label
            hooks.append(convert(hook, source))
    return hooks


class Dumper(yaml.SafeDumper):
    """Block style everywhere except flat lists (`types: [python, pyi]`), no line folding."""


def _represent_list(dumper: Dumper, data: list) -> yaml.Node:
    flat = all(not isinstance(item, (dict, list)) for item in data)
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=flat)


Dumper.add_representer(list, _represent_list)


def dump(data: object) -> str:
    return yaml.dump(data, Dumper=Dumper, sort_keys=False, default_flow_style=False, allow_unicode=True, width=4096)


def render_hooks_file(hooks: list[dict]) -> str:
    return HOOKS_HEADER + "\n" + "\n".join(dump([h]) for h in hooks)


def render_root_config(hooks: list[dict]) -> str:
    config = yaml.safe_load(SELF_LINT.read_text())
    by_id = {h["id"]: h for h in hooks}
    selected = []
    for entry in config["hooks"]:
        hook_id = entry["id"]
        if hook_id in by_id:
            if {"entry", "language"} & entry.keys():
                sys.exit(
                    f"{SELF_LINT.name}: {hook_id!r} defines entry/language, but {hook_id!r} is also a "
                    f"published hook in {HOOKS_FILE.name}; rename this repo-only hook, or drop "
                    "entry/language to use the published one"
                )
            selected.append({**by_id[hook_id], **entry})
            continue
        # Not a published hook: must be a complete local hook for this repo only.
        missing = {"name", "entry", "language"} - entry.keys()
        if missing:
            sys.exit(
                f"{SELF_LINT.name}: {hook_id!r} is not in {HOOKS_FILE.name}; "
                f"fix the id or define {', '.join(sorted(missing))}"
            )
        selected.append(entry)

    root = {k: v for k, v in config.items() if k != "hooks"}
    root["repos"] = [{"repo": "local", "hooks": selected}]
    return ROOT_CONFIG_HEADER + "\n" + dump(root)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if a generated file is out of date")
    args = parser.parse_args()

    hooks = build_hooks()
    outputs = {HOOKS_FILE: render_hooks_file(hooks), ROOT_CONFIG: render_root_config(hooks)}

    stale = []
    for path, new in outputs.items():
        old = path.read_text() if path.exists() else ""
        if new == old:
            print(f"{path.name} is up to date")
            continue
        stale.append(path.name)
        sys.stdout.writelines(
            difflib.unified_diff(old.splitlines(True), new.splitlines(True), f"{path.name} (current)", "generated")
        )
        if not args.check:
            path.write_text(new)
            print(f"wrote {path.name}")

    if args.check and stale:
        print(f"\nout of date: {', '.join(stale)}; run scripts/sync.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
